"""Add visitor_number and biometric fields to Visitor

Revision ID: 264411a402df
Revises: ac36f849fdd6
Create Date: 2026-09-27 13:40:55.670885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264411a402df'
down_revision = 'ac36f849fdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
