"""add anomaly_flag to visitor

Revision ID: 4e782d877afd
Revises: 80a5fd39d1cb
Create Date: 2026-09-27 11:24:11.673852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e782d877afd'
down_revision = '80a5fd39d1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anomaly_flag', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_column('anomaly_flag')

    # ### end Alembic commands ###
