"""Add biometric_enrolled to Visitor

Revision ID: 7165c8bbd4d8
Revises: 4e782d877afd
Create Date: 2026-09-27 13:07:07.246161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7165c8bbd4d8'
down_revision = '4e782d877afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_enrolled', sa.Boolean(), nullable=False))
        batch_op.alter_column('fingerprint_template',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('fingerprint_template',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.drop_column('biometric_enrolled')

    # ### end Alembic commands ###
