"""Initial schema with naming convention

Revision ID: 80a5fd39d1cb
Revises: 
Create Date: 2026-09-26 23:51:35.176164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a5fd39d1cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_forecasts',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_period', sa.String(length=20), nullable=True),
    sa.Column('predicted_population', sa.Integer(), nullable=True),
    sa.Column('predicted_admissions', sa.Integer(), nullable=True),
    sa.Column('predicted_releases', sa.Integer(), nullable=True),
    sa.Column('predicted_overcrowding_risk', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('current_capacity', sa.Integer(), nullable=True),
    sa.Column('projected_capacity', sa.Integer(), nullable=True),
    sa.Column('capacity_utilization', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('based_on_data_from', sa.Date(), nullable=True),
    sa.Column('based_on_data_to', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by_model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('forecast_id', name=op.f('pk_population_forecasts'))
    )
    with op.batch_alter_table('population_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_forecasts_forecast_date'), ['forecast_date'], unique=False)

    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_role_name'), ['role_name'], unique=True)

    op.create_table('visitors',
    sa.Column('visitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('national_id_number', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('fingerprint_template', sa.LargeBinary(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('risk_rating', sa.String(length=20), nullable=True),
    sa.Column('total_visits_made', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('visitor_id', name=op.f('pk_visitors'))
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_is_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_national_id_number'), ['national_id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitors_passport_number'), ['passport_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitors_phone_number'), ['phone_number'], unique=False)

    op.create_table('user_accounts',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('fingerprint_template', sa.LargeBinary(), nullable=True),
    sa.Column('biometric_enrolled', sa.Boolean(), nullable=False),
    sa.Column('biometric_enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('biometric_quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_accounts_role_id_roles')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_accounts'))
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_accounts_username'), ['username'], unique=True)

    op.create_table('visitor_patterns',
    sa.Column('pattern_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('avg_visit_frequency_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_visit_duration_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('typical_visit_days', sa.Text(), nullable=True),
    sa.Column('typical_visit_hours', sa.Text(), nullable=True),
    sa.Column('unusual_time_visits', sa.Integer(), nullable=True),
    sa.Column('multiple_inmate_associations', sa.Integer(), nullable=True),
    sa.Column('rapid_succession_visits', sa.Integer(), nullable=True),
    sa.Column('inconsistent_relationship_claims', sa.Integer(), nullable=True),
    sa.Column('total_flagged_visits', sa.Integer(), nullable=True),
    sa.Column('last_flagged_date', sa.Date(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], name=op.f('fk_visitor_patterns_visitor_id_visitors')),
    sa.PrimaryKeyConstraint('pattern_id', name=op.f('pk_visitor_patterns'))
    )
    with op.batch_alter_table('visitor_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_patterns_visitor_id'), ['visitor_id'], unique=True)

    op.create_table('ai_analysis_log',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('detailed_result', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('action_taken_by', sa.Integer(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_taken_by'], ['user_accounts.user_id'], name=op.f('fk_ai_analysis_log_action_taken_by_user_accounts')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_accounts.user_id'], name=op.f('fk_ai_analysis_log_reviewed_by_user_accounts')),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_ai_analysis_log'))
    )
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_analysis_timestamp'), ['analysis_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_analysis_type'), ['analysis_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_is_reviewed'), ['is_reviewed'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_severity'), ['severity'], unique=False)

    op.create_table('audit_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], name=op.f('fk_audit_events_user_id_user_accounts')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_category'), ['event_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_timestamp'), ['event_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('edit_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_label', sa.String(length=200), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['user_accounts.user_id'], name=op.f('fk_edit_requests_requested_by_user_accounts')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_accounts.user_id'], name=op.f('fk_edit_requests_reviewed_by_user_accounts')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_edit_requests'))
    )
    with op.batch_alter_table('edit_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_requests_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_requests_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_requests_target_type'), ['target_type'], unique=False)

    op.create_table('inmates',
    sa.Column('inmate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inmate_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('alias_names', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('tribe', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('national_id_number', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=150), nullable=True),
    sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.Column('next_of_kin_address', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('distinguishing_marks', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('crime_category', sa.String(length=100), nullable=True),
    sa.Column('crime_description', sa.Text(), nullable=True),
    sa.Column('court_case_number', sa.String(length=50), nullable=True),
    sa.Column('sentencing_court', sa.String(length=100), nullable=True),
    sa.Column('judge_name', sa.String(length=100), nullable=True),
    sa.Column('sentence_type', sa.String(length=50), nullable=True),
    sa.Column('sentence_duration', sa.String(length=50), nullable=True),
    sa.Column('sentence_start_date', sa.Date(), nullable=True),
    sa.Column('expected_release_date', sa.Date(), nullable=True),
    sa.Column('actual_release_date', sa.Date(), nullable=True),
    sa.Column('cell_block', sa.String(length=20), nullable=True),
    sa.Column('cell_number', sa.String(length=20), nullable=True),
    sa.Column('security_classification', sa.String(length=20), nullable=True),
    sa.Column('fingerprint_template', sa.LargeBinary(), nullable=True),
    sa.Column('biometric_enrolled', sa.Boolean(), nullable=True),
    sa.Column('biometric_enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('biometric_quality_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_admission_date', sa.Date(), nullable=False),
    sa.Column('total_admissions', sa.Integer(), nullable=True),
    sa.Column('has_medical_condition', sa.Boolean(), nullable=True),
    sa.Column('medical_alert', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('violence_history', sa.Boolean(), nullable=True),
    sa.Column('escape_attempt_history', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.user_id'], name=op.f('fk_inmates_created_by_user_accounts')),
    sa.PrimaryKeyConstraint('inmate_id', name=op.f('pk_inmates'))
    )
    with op.batch_alter_table('inmates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inmates_biometric_enrolled'), ['biometric_enrolled'], unique=False)
        batch_op.create_index(batch_op.f('ix_inmates_cell_block'), ['cell_block'], unique=False)
        batch_op.create_index(batch_op.f('ix_inmates_crime_category'), ['crime_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inmates_expected_release_date'), ['expected_release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inmates_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inmates_inmate_number'), ['inmate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inmates_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.user_id'], name=op.f('fk_notifications_user_id_user_accounts')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user_accounts.user_id'], name=op.f('fk_system_settings_updated_by_user_accounts')),
    sa.PrimaryKeyConstraint('setting_id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('admission_episodes',
    sa.Column('episode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inmate_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('admission_type', sa.String(length=20), nullable=False),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('releasing_facility', sa.String(length=100), nullable=True),
    sa.Column('receiving_officer_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_type', sa.String(length=30), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('releasing_officer_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inmate_id'], ['inmates.inmate_id'], name=op.f('fk_admission_episodes_inmate_id_inmates')),
    sa.ForeignKeyConstraint(['receiving_officer_id'], ['user_accounts.user_id'], name=op.f('fk_admission_episodes_receiving_officer_id_user_accounts')),
    sa.ForeignKeyConstraint(['releasing_officer_id'], ['user_accounts.user_id'], name=op.f('fk_admission_episodes_releasing_officer_id_user_accounts')),
    sa.PrimaryKeyConstraint('episode_id', name=op.f('pk_admission_episodes'))
    )
    with op.batch_alter_table('admission_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admission_episodes_inmate_id'), ['inmate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_episodes_is_current'), ['is_current'], unique=False)

    op.create_table('disciplinary_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inmate_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('punishment_assigned', sa.Text(), nullable=True),
    sa.Column('punishment_start_date', sa.Date(), nullable=True),
    sa.Column('punishment_end_date', sa.Date(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inmate_id'], ['inmates.inmate_id'], name=op.f('fk_disciplinary_logs_inmate_id_inmates')),
    sa.ForeignKeyConstraint(['reported_by'], ['user_accounts.user_id'], name=op.f('fk_disciplinary_logs_reported_by_user_accounts')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_disciplinary_logs'))
    )
    with op.batch_alter_table('disciplinary_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disciplinary_logs_inmate_id'), ['inmate_id'], unique=False)

    op.create_table('medical_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inmate_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_prescribed', sa.Text(), nullable=True),
    sa.Column('medication_details', sa.Text(), nullable=True),
    sa.Column('attending_medical_officer', sa.String(length=150), nullable=True),
    sa.Column('referred_to_hospital', sa.Boolean(), nullable=True),
    sa.Column('hospital_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inmate_id'], ['inmates.inmate_id'], name=op.f('fk_medical_records_inmate_id_inmates')),
    sa.ForeignKeyConstraint(['recorded_by'], ['user_accounts.user_id'], name=op.f('fk_medical_records_recorded_by_user_accounts')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_medical_records'))
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_inmate_id'), ['inmate_id'], unique=False)

    op.create_table('visit_logs',
    sa.Column('visit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('inmate_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('visit_type', sa.String(length=30), nullable=False),
    sa.Column('purpose_of_visit', sa.String(length=100), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('items_brought', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inmate_id'], ['inmates.inmate_id'], name=op.f('fk_visit_logs_inmate_id_inmates')),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user_accounts.user_id'], name=op.f('fk_visit_logs_processed_by_id_user_accounts')),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], name=op.f('fk_visit_logs_visitor_id_visitors')),
    sa.PrimaryKeyConstraint('visit_id', name=op.f('pk_visit_logs'))
    )
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_logs_anomaly_flag'), ['anomaly_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_check_in_time'), ['check_in_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_inmate_id'), ['inmate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_logs_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_logs_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_inmate_id'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_check_in_time'))
        batch_op.drop_index(batch_op.f('ix_visit_logs_anomaly_flag'))

    op.drop_table('visit_logs')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_inmate_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('disciplinary_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disciplinary_logs_inmate_id'))

    op.drop_table('disciplinary_logs')
    with op.batch_alter_table('admission_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admission_episodes_is_current'))
        batch_op.drop_index(batch_op.f('ix_admission_episodes_inmate_id'))

    op.drop_table('admission_episodes')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_setting_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('inmates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inmates_status'))
        batch_op.drop_index(batch_op.f('ix_inmates_inmate_number'))
        batch_op.drop_index(batch_op.f('ix_inmates_full_name'))
        batch_op.drop_index(batch_op.f('ix_inmates_expected_release_date'))
        batch_op.drop_index(batch_op.f('ix_inmates_crime_category'))
        batch_op.drop_index(batch_op.f('ix_inmates_cell_block'))
        batch_op.drop_index(batch_op.f('ix_inmates_biometric_enrolled'))

    op.drop_table('inmates')
    with op.batch_alter_table('edit_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_requests_target_type'))
        batch_op.drop_index(batch_op.f('ix_edit_requests_target_id'))
        batch_op.drop_index(batch_op.f('ix_edit_requests_status'))
        batch_op.drop_index(batch_op.f('ix_edit_requests_requested_by'))
        batch_op.drop_index(batch_op.f('ix_edit_requests_requested_at'))

    op.drop_table('edit_requests')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_category'))

    op.drop_table('audit_events')
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_severity'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_is_reviewed'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_analysis_type'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_analysis_timestamp'))

    op.drop_table('ai_analysis_log')
    with op.batch_alter_table('visitor_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_patterns_visitor_id'))

    op.drop_table('visitor_patterns')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_email'))

    op.drop_table('user_accounts')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_phone_number'))
        batch_op.drop_index(batch_op.f('ix_visitors_passport_number'))
        batch_op.drop_index(batch_op.f('ix_visitors_national_id_number'))
        batch_op.drop_index(batch_op.f('ix_visitors_is_flagged'))
        batch_op.drop_index(batch_op.f('ix_visitors_full_name'))

    op.drop_table('visitors')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_name'))

    op.drop_table('roles')
    with op.batch_alter_table('population_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_forecasts_forecast_date'))

    op.drop_table('population_forecasts')
    # ### end Alembic commands ###
