"""Add visitor_number and biometric fields to Visitor

Revision ID: 991799592304
Revises: 264411a402df
Create Date: 2026-09-27 14:25:12.747116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991799592304'
down_revision = '264411a402df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cell_blocks')),
    sa.UniqueConstraint('name', name=op.f('uq_cell_blocks_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_blocks')
    # ### end Alembic commands ###
