"""Add visitor_number and biometric fields to Visitor

Revision ID: ac36f849fdd6
Revises: 7165c8bbd4d8
Create Date: 2026-09-27 13:33:42.048223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac36f849fdd6'
down_revision = '7165c8bbd4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('biometric_enrollment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('biometric_quality_score', sa.Integer(), nullable=True))
        batch_op.alter_column('fingerprint_template',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_visitors_visitor_number'), ['visitor_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_visitor_number'))
        batch_op.alter_column('fingerprint_template',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('biometric_quality_score')
        batch_op.drop_column('biometric_enrollment_date')
        batch_op.drop_column('visitor_number')

    # ### end Alembic commands ###
